name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Android CI [useK2Uast=${{ matrix.useK2Uast }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        useK2Uast: [true, false]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Check Assemble Lint
      run: ./gradlew check assembleDebug bundleDebug lintDebug -Pandroid.lint.useK2Uast=${{ matrix.useK2Uast }} -Pandroid.experimental.lint.version=8.5.0-alpha02 --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-${{ matrix.useK2Uast }}.apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-${{ matrix.useK2Uast }}.aab
        path: app/build/outputs/bundle/debug/app-debug.aab
