name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Check
      uses: gradle/gradle-build-action@243af859f8ca30903d9d7f7936897ca0358ba691 # v2.7.1
      with:
        arguments: check --stacktrace
    - name: Assemble
      uses: gradle/gradle-build-action@243af859f8ca30903d9d7f7936897ca0358ba691 # v2.7.1
      with:
        arguments: assembleDebug bundleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.aab
        path: app/build/outputs/bundle/debug/app-debug.aab
