name: 🐘 Gradle Wrapper updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle-update/update-gradle-wrapper-action@9cca748ef7cfd967bc3a5c39e15a7aa229ad1b3d # v2.0.1
        with:
          set-distribution-checksum: false
